
package GUI;

import javax.media.j3d.Canvas3D;
import Model.Universo;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;

public class ControlWindow extends JFrame {
    private Universo universe;

    public ControlWindow(Canvas3D canvas, Universo anUniverse) {
        super();
        universe = anUniverse;
        initComponents();
        setLocation (920, 100);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                closeApp(0);
            }
        });
        Visualization visualization = new Visualization (this, false, canvas);
        visualization.setVisible(true);
        pack();
    }

    /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRotacion = new javax.swing.JPanel();
        aumentarRotacion = new javax.swing.JButton();
        disminuirRotacion = new javax.swing.JButton();
        panelDesplazamiento = new javax.swing.JPanel();
        aumentarDesplazamiento = new javax.swing.JButton();
        disminuirDesplazamiento = new javax.swing.JButton();
        panelElevacion = new javax.swing.JPanel();
        aumentarElevacion = new javax.swing.JButton();
        disminuirElevacion = new javax.swing.JButton();
        exitApp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Control");
        setMinimumSize(new java.awt.Dimension(300, 345));
        getContentPane().setLayout(new java.awt.GridLayout(5, 0));

        panelRotacion.setBorder(javax.swing.BorderFactory.createTitledBorder("Rotación"));

        aumentarRotacion.setText("Aumentar");
        aumentarRotacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aumentarRotacionActionPerformed(evt);
            }
        });
        panelRotacion.add(aumentarRotacion);

        disminuirRotacion.setText("Disminuir");
        disminuirRotacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disminuirRotacionActionPerformed(evt);
            }
        });
        panelRotacion.add(disminuirRotacion);

        getContentPane().add(panelRotacion);

        panelDesplazamiento.setBorder(javax.swing.BorderFactory.createTitledBorder("Desplazamiento"));

        aumentarDesplazamiento.setText("Aumentar");
        aumentarDesplazamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aumentarDesplazamientoActionPerformed(evt);
            }
        });
        panelDesplazamiento.add(aumentarDesplazamiento);

        disminuirDesplazamiento.setText("Disminuir");
        disminuirDesplazamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disminuirDesplazamientoActionPerformed(evt);
            }
        });
        panelDesplazamiento.add(disminuirDesplazamiento);

        getContentPane().add(panelDesplazamiento);

        panelElevacion.setBorder(javax.swing.BorderFactory.createTitledBorder("Elevación"));

        aumentarElevacion.setText("Aumentar");
        aumentarElevacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aumentarElevacionActionPerformed(evt);
            }
        });
        panelElevacion.add(aumentarElevacion);

        disminuirElevacion.setText("Disminuir");
        disminuirElevacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disminuirElevacionActionPerformed(evt);
            }
        });
        panelElevacion.add(disminuirElevacion);

        getContentPane().add(panelElevacion);

        exitApp.setText("Salir");
        exitApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitAppActionPerformed(evt);
            }
        });
        getContentPane().add(exitApp);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitAppActionPerformed
        // TODO add your handling code here:
        closeApp(0);
    }//GEN-LAST:event_exitAppActionPerformed

    private void aumentarRotacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aumentarRotacionActionPerformed
        // TODO add your handling code here:
        universe.aumentarRotacion();
    }//GEN-LAST:event_aumentarRotacionActionPerformed

    private void disminuirRotacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disminuirRotacionActionPerformed
        // TODO add your handling code here:
        universe.disminuirRotacion();
    }//GEN-LAST:event_disminuirRotacionActionPerformed

    private void aumentarDesplazamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aumentarDesplazamientoActionPerformed
        // TODO add your handling code here:
        universe.aumentarDesplazamiento();
    }//GEN-LAST:event_aumentarDesplazamientoActionPerformed

    private void disminuirDesplazamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disminuirDesplazamientoActionPerformed
        // TODO add your handling code here:
        universe.disminuirDesplazamiento();
    }//GEN-LAST:event_disminuirDesplazamientoActionPerformed

    private void aumentarElevacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aumentarElevacionActionPerformed
        // TODO add your handling code here:
        universe.aumentarElevacion();
    }//GEN-LAST:event_aumentarElevacionActionPerformed

    private void disminuirElevacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disminuirElevacionActionPerformed
        // TODO add your handling code here:
        universe.disminuirElevacion();
    }//GEN-LAST:event_disminuirElevacionActionPerformed

    public void showWindow () {
        setVisible (true);
    }

    void closeApp (int code) {
        universe.closeApp(code);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aumentarDesplazamiento;
    private javax.swing.JButton aumentarElevacion;
    private javax.swing.JButton aumentarRotacion;
    private javax.swing.JButton disminuirDesplazamiento;
    private javax.swing.JButton disminuirElevacion;
    private javax.swing.JButton disminuirRotacion;
    private javax.swing.JButton exitApp;
    private javax.swing.JPanel panelDesplazamiento;
    private javax.swing.JPanel panelElevacion;
    private javax.swing.JPanel panelRotacion;
    // End of variables declaration//GEN-END:variables
}
