
package GUI;

import javax.media.j3d.Canvas3D;
import Model.Universo;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;

public class ControlWindow extends JFrame {

    private Universo universe;

    public ControlWindow(Canvas3D canvas, Canvas3D canvasVariable, Universo anUniverse) {
        super();
        universe = anUniverse;
        initComponents();
        setLocation (915, 338);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                closeApp(0);
            }
        });
        Visualization visualization = new Visualization (this, false, canvas, 915, 0);
        visualization.setVisible(true);
        Visualization visualizationVariable = new Visualization (this, false, canvasVariable, 0, 0);
        visualizationVariable.setVisible(true);
        pack();
    }

  /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        primitiveGroup = new javax.swing.ButtonGroup();
        appearanceGroup = new javax.swing.ButtonGroup();
        camaraPerspectiva = new javax.swing.JButton();
        camaraLuna = new javax.swing.JButton();
        camaraNave = new javax.swing.JButton();
        exitApp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Control");
        setMinimumSize(new java.awt.Dimension(300, 300));
        getContentPane().setLayout(new java.awt.GridLayout(5, 0));

        camaraPerspectiva.setText("Camara Perspectiva");
        camaraPerspectiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                camaraPerspectivaActionPerformed(evt);
            }
        });
        getContentPane().add(camaraPerspectiva);

        camaraLuna.setText("Camara Luna");
        camaraLuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                camaraLunaActionPerformed(evt);
            }
        });
        getContentPane().add(camaraLuna);

        camaraNave.setText("Camara Nave");
        camaraNave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                camaraNaveActionPerformed(evt);
            }
        });
        getContentPane().add(camaraNave);

        exitApp.setText("Salir");
        exitApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitAppActionPerformed(evt);
            }
        });
        getContentPane().add(exitApp);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitAppActionPerformed
        // TODO add your handling code here:
        closeApp(0);
    }//GEN-LAST:event_exitAppActionPerformed

    private void camaraLunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_camaraLunaActionPerformed
        // TODO add your handling code here:
        universe.activarCamaraLuna();
    }//GEN-LAST:event_camaraLunaActionPerformed

    private void camaraPerspectivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_camaraPerspectivaActionPerformed
        // TODO add your handling code here:
        universe.activarCamaraPerspectiva();
    }//GEN-LAST:event_camaraPerspectivaActionPerformed

    private void camaraNaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_camaraNaveActionPerformed
        // TODO add your handling code here:
        universe.activarCamaraNave();
    }//GEN-LAST:event_camaraNaveActionPerformed

    public void showWindow () {
        setVisible(true);
    }

    void closeApp (int code) {
        universe.closeApp(code);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup appearanceGroup;
    private javax.swing.JButton camaraLuna;
    private javax.swing.JButton camaraNave;
    private javax.swing.JButton camaraPerspectiva;
    private javax.swing.JButton exitApp;
    private javax.swing.ButtonGroup primitiveGroup;
    // End of variables declaration//GEN-END:variables
    
}
